language: csharp
dist: trusty
mono: none
dotnet: 2.1.3

env:
  - NPGSQL_TEST_DB: '"Host=localhost;Database=npgsql_tests;Username=npgsql_tests;Password=npgsql_tests"'

before_install:
  - wget https://cdn.crate.io/downloads/deb/DEB-GPG-KEY-crate
  - sudo apt-key add DEB-GPG-KEY-crate
  - deb https://cdn.crate.io/downloads/deb/testing/ trusty main
  - deb-src https://cdn.crate.io/downloads/deb/testing/ trusty main
  - sudo apt-get update
  - sudo apt-get install crate
  - sudo service crate restart

before_script:
  - dotnet restore -v Minimal
script:
  - dotnet build "test/Npgsql.Tests" -c Debug -f netcoreapp2.0
  - dotnet build "test/Npgsql.PluginTests" -c Debug -f netcoreapp2.0
  - dotnet test "test/Npgsql.Tests/Npgsql.Tests.csproj" -c Debug -f netcoreapp2.0
  - dotnet test "test/Npgsql.PluginTests/Npgsql.PluginTests.csproj" -c Debug -f netcoreapp2.0

cache:
  directories:
    - $HOME/.nuget/packages

